- name: Deployment of central server
  hosts: central
  become: true

  roles:
    - prometheus
    - consul
    - rabbitmq

  vars:
    prometheus_components: [ "prometheus", "node_exporter" ]
    prometheus_conf_main: files/prometheus/prometheus.yml
    consul_server_ip: "192.168.55.254"
    consul_server: true

  tasks:

    - name: Uploading required scripts
      copy:
        src: "{{ item }}"
        dest: /usr/local/bin
        mode: 0755
      with_items: ['sender.py', 'clog.sh']
