---
- name: Installing default packages set for Kafka
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - "yum-utils"

- name: install the 'Development tools' package group
  yum:
    name: "@Development tools"
    state: present

- name: install the IUS rpm
  yum:
    name: https://centos7.iuscommunity.org/ius-release.rpm
    state: present

- name: Installing default packages set for Python
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - "python36u"
    - "python36u-pip"
    - "python36u-devel"

- name: Uploading Python scripts for Kafka
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
  loop:
    - { src: "files/solution1.py", dst: "/usr/local/bin/" }
    - { src: "files/solution2.py", dst: "/usr/local/bin" }
    - { src: "files/producer.service", dst: "/etc/systemd/system/" }
    - { src: "files/consumer.service", dst: "/etc/systemd/system/" }

- pip:
    name: kafka-python

- name: Making sure that Py script services are up
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    daemon_reload: yes
  loop:
    - producer
    - consumer